# Generated by Django 3.2.13 on 2022-06-21 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indistribution_error', models.BooleanField(blank=True, default=False)),
                ('outofdistribution_error', models.BooleanField(blank=True, default=False)),
                ('false_observation', models.BooleanField(blank=True, default=False)),
                ('failing_to_oberserve', models.BooleanField(blank=True, default=False)),
                ('incomplete_observation', models.BooleanField(blank=True, default=False)),
                ('critical_quality', models.BooleanField(blank=True, default=False)),
                ('violation', models.BooleanField(blank=True, default=False)),
                ('context_error', models.BooleanField(blank=True, default=False)),
                ('other_mode', models.CharField(blank=True, max_length=200)),
                ('physical_harm', models.BooleanField(blank=True, default=False)),
                ('psychological_harm', models.BooleanField(blank=True, default=False)),
                ('financial_damage', models.BooleanField(blank=True, default=False)),
                ('reputational_damage', models.BooleanField(blank=True, default=False)),
                ('personal_privacy_violation', models.BooleanField(blank=True, default=False)),
                ('annoyance', models.BooleanField(blank=True, default=False)),
                ('discrimination', models.BooleanField(blank=True, default=False)),
                ('exclusion', models.BooleanField(blank=True, default=False)),
                ('harmful_content', models.BooleanField(blank=True, default=False)),
                ('public_misinformation', models.BooleanField(blank=True, default=False)),
                ('political_conflict', models.BooleanField(blank=True, default=False)),
                ('legal_breech', models.BooleanField(blank=True, default=False)),
                ('economic_damage', models.BooleanField(blank=True, default=False)),
                ('public_privacy_breech', models.BooleanField(blank=True, default=False)),
                ('failure_severity', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-1)])),
                ('sample', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample')),
            ],
        ),
    ]
