# Generated by Django 3.2.13 on 2022-06-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='failure',
        ),
    ]
