# Generated by Django 3.2.13 on 2022-05-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Sample',
        ),
    ]
