# Generated by Django 3.2.13 on 2022-06-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='sample',
            field=models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample'),
        ),
    ]
