# Generated by Django 3.2.13 on 2022-06-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0002_remove_sample_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='failure',
            field=models.BooleanField(default=False),
        ),
    ]
