# Generated by Django 3.2.13 on 2022-06-21 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0002_alter_failure_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='failure_severity',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(-1)]),
        ),
    ]
