# Generated by Django 3.2.13 on 2022-05-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0002_rename_question_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='name',
        ),
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
