# Generated by Django 3.2.13 on 2022-07-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0002_scenario_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='name',
        ),
        migrations.AddField(
            model_name='query',
            name='persona',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.persona'),
        ),
        migrations.AddField(
            model_name='query',
            name='scenario',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='context',
            field=models.TextField(blank=True),
        ),
    ]
