# Generated by Django 3.2.13 on 2022-05-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0003_auto_20220522_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detections', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.AddField(
            model_name='sample',
            name='model_prediction',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fdd_app.modelprediction'),
            preserve_default=False,
        ),
    ]
