# Generated by Django 3.2.13 on 2022-07-18 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0003_auto_20220718_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.persona'),
        ),
        migrations.AlterField(
            model_name='query',
            name='scenario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='persona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.persona'),
        ),
    ]
