# Generated by Django 3.2.13 on 2022-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0004_auto_20220524_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='model_prediction',
        ),
        migrations.AddField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModelPrediction',
        ),
    ]
