# Generated by Django 3.2.13 on 2022-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0004_auto_20220718_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
