# Generated by Django 3.2.13 on 2022-06-27 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0005_auto_20220627_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectation',
            name='sample',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample'),
        ),
    ]
