# Generated by Django 3.2.13 on 2022-07-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0005_scenario_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='name',
            new_name='persona_name',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='input_query',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='context',
            new_name='context_description',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='name',
            new_name='context_name',
        ),
    ]
