# Generated by Django 3.2.13 on 2022-06-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0006_alter_expectation_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expectation',
            name='box',
        ),
        migrations.AddField(
            model_name='expectation',
            name='xmax',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='expectation',
            name='xmin',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='expectation',
            name='ymax',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='expectation',
            name='ymin',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
