# Generated by Django 3.2.13 on 2022-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0006_auto_20220718_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='context_description',
            new_name='environment',
        ),
        migrations.AddField(
            model_name='persona',
            name='age',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='persona',
            name='attitutes_towards_ai',
            field=models.TextField(blank=True),
        ),
    ]
