# Generated by Django 3.2.13 on 2022-06-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0007_auto_20220627_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectation',
            old_name='ymax',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='xmax',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='xmin',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='ymin',
            new_name='y',
        ),
    ]
