# Generated by Django 3.2.13 on 2022-07-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0007_auto_20220719_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='persona_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='context_name',
            new_name='name',
        ),
    ]
