# Generated by Django 3.2.13 on 2022-07-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0008_auto_20220719_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='persona',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.persona'),
        ),
        migrations.AddField(
            model_name='sample',
            name='scenario',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.scenario'),
        ),
    ]
