# Generated by Django 3.2.13 on 2022-07-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0009_auto_20220719_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='persona',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
