# Generated by Django 3.2.13 on 2022-07-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0010_auto_20220719_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='image',
            field=models.ImageField(default='personas/default_persona', upload_to='personas/'),
        ),
    ]
