# Generated by Django 3.2.13 on 2022-06-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0010_auto_20220630_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='sample',
        ),
    ]
