# Generated by Django 3.2.13 on 2022-07-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0011_persona_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='environment',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='scenario',
            old_name='location',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='age',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='attitutes_towards_ai',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='occupation',
        ),
    ]
