# Generated by Django 3.2.13 on 2022-07-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0012_auto_20220722_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='failure_effects',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='persona',
            name='image',
            field=models.ImageField(default='personas/default_persona.jpeg', upload_to='personas/'),
        ),
    ]
