# Generated by Django 3.2.13 on 2022-06-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0012_failure_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failure',
            name='sample',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample'),
        ),
    ]
