# Generated by Django 3.2.13 on 2022-07-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0013_auto_20220726_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='expectation',
            name='indist',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='expectation',
            name='outdist',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
