# Generated by Django 3.2.13 on 2022-06-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0013_alter_failure_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='sample',
        ),
        migrations.AddField(
            model_name='failure',
            name='samples',
            field=models.ManyToManyField(blank=True, to='fdd_app.Sample'),
        ),
    ]
