# Generated by Django 3.2.13 on 2022-08-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0014_auto_20220729_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='objectives_and_goals',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='personality',
        ),
    ]
