# Generated by Django 3.2.13 on 2022-08-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0015_auto_20220805_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='name',
        ),
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
