# Generated by Django 3.2.13 on 2022-06-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0015_auto_20220630_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='id',
        ),
        migrations.AlterField(
            model_name='failure',
            name='sample',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='fdd_app.sample'),
        ),
    ]
