# Generated by Django 3.2.13 on 2022-08-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0016_auto_20220805_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='uploaded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
