# Generated by Django 4.1 on 2022-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0018_sample_generated_sample_labelled_sample_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='assessed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
