# Generated by Django 3.2.13 on 2022-07-04 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0018_alter_model_prediction_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectation', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.expectation')),
                ('model_prediction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.model_prediction')),
                ('sample', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample')),
            ],
        ),
    ]
