# Generated by Django 4.1 on 2022-08-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0019_sample_assessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='outofdistribution',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
