# Generated by Django 3.2.13 on 2022-07-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0019_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='additional_observation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='critical_quality_box',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='critical_quality_score',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='failing_to_oberserve',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='false_observation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='incomplete_observation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='true_positive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
