# Generated by Django 3.2.13 on 2022-07-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0020_auto_20220704_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='failing_to_oberserve',
            new_name='indistribution',
        ),
    ]
