# Generated by Django 3.2.13 on 2022-07-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0021_rename_failing_to_oberserve_match_indistribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expectation',
            field=models.ForeignKey(default='no object', on_delete=django.db.models.deletion.CASCADE, to='fdd_app.expectation'),
        ),
        migrations.AlterField(
            model_name='match',
            name='model_prediction',
            field=models.ForeignKey(default='no object', on_delete=django.db.models.deletion.CASCADE, to='fdd_app.model_prediction'),
        ),
    ]
