# Generated by Django 4.1 on 2022-08-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0022_suggestion_challenge_suggestion_challenge_again_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='sample',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='fdd_app.sample'),
        ),
    ]
