# Generated by Django 3.2.13 on 2022-07-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0022_auto_20220704_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='expectation',
            field=models.ForeignKey(blank=True, default='no object', on_delete=django.db.models.deletion.CASCADE, to='fdd_app.expectation'),
        ),
        migrations.AlterField(
            model_name='match',
            name='model_prediction',
            field=models.ForeignKey(blank=True, default='no object', on_delete=django.db.models.deletion.CASCADE, to='fdd_app.model_prediction'),
        ),
    ]
