# Generated by Django 4.1 on 2022-08-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0023_suggestion_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='expectation_label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
