# Generated by Django 3.2.13 on 2022-07-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0025_auto_20220704_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='additional_observation',
            new_name='additional_detection',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='false_observation',
            new_name='false_detection',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='incomplete_observation',
            new_name='missing_detection',
        ),
    ]
