# Generated by Django 3.2.13 on 2022-07-05 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0026_auto_20220705_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectation',
            old_name='width',
            new_name='xmax',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='x',
            new_name='xmin',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='height',
            new_name='ymax',
        ),
        migrations.RenameField(
            model_name='expectation',
            old_name='y',
            new_name='ymin',
        ),
    ]
