# Generated by Django 3.2.13 on 2022-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0028_auto_20220705_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='failing_to_detect',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
