# Generated by Django 3.2.13 on 2022-07-06 09:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0029_match_failing_to_detect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='additional_detection',
            new_name='unnecessary_detection',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='failing_to_oberserve',
        ),
        migrations.RemoveField(
            model_name='failure',
            name='sample',
        ),
        migrations.AddField(
            model_name='failure',
            name='sample_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='failure',
            name='other_mode',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
    ]
