# Generated by Django 3.2.13 on 2022-07-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0030_auto_20220706_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='failure_severity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
