# Generated by Django 3.2.13 on 2022-07-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdd_app', '0031_match_failure_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='has_failure',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
